/* Local review workspace; standalone exports remain backend-free. */
(()=>{'use strict';
if(location.protocol!=='http:'||!/^\/courses\/course-[a-f0-9]{16}\//.test(location.pathname))return;
const C=window.COURSE_DATA;if(!C)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=C.files.flatMap(f=>f.pages),units=pages.flatMap(p=>p.units.filter(u=>!u.reviewOnly));
const d=document.createElement('dialog');d.id='review-dialog';
d.innerHTML=`<div class="dialog-heading"><div><h2>讲义复核</h2><p id="review-count" class="small muted"></p></div><button type="button" class="icon-button" id="review-close" aria-label="关闭复核">×</button></div>
<div class="review-workspace"><aside class="review-list-panel"><label class="review-filter">查看<select id="review-filter"><option value="pending">待复核内容</option><option value="all">全部正文</option></select></label><div id="review-list"></div></aside>
<section class="review-source-panel"><div class="review-source-heading"><span id="review-page-label"></span><button type="button" id="review-jump" class="text-button">定位正文 ↗</button></div><div class="review-original"><img id="review-page-image" alt="原讲义页面"><span id="review-position"></span></div><p id="review-position-note" class="small muted"></p></section>
<form id="review-form"><p id="review-reason" class="small muted"></p><div id="review-unit-fields"><label class="review-field">原文<textarea id="review-source" maxlength="30000" rows="4"></textarea></label><div class="review-translation-heading"><label for="review-translation">译文</label><button type="button" id="review-translate" class="button">生成译文草稿</button></div><textarea id="review-translation" maxlength="30000" rows="4"></textarea><p id="review-draft-label" class="small muted"></p><label class="review-field" id="review-math-label">LaTeX 公式<textarea id="review-math" rows="2" maxlength="30000"></textarea></label><details class="review-history"><summary>原始识别文本与修正历史</summary><pre id="review-history"></pre></details></div>
<div id="review-page-fields" hidden><p>请核对整页表格的数字、符号和行列。确认页面复核不会自动清除单元自身的疑点。</p></div><p id="review-error" role="status"></p><div class="review-editor-actions"><button type="button" class="button" id="review-reset">撤销未保存修改</button><button type="submit" class="button primary" id="review-save">保存并下一项</button></div></form></div>
<div class="dialog-footer"><button type="button" class="button" id="review-prev">上一项</button><span class="small muted">Ctrl / ⌘ + Enter 保存 · 草稿确认后才写入正文</span><button type="button" class="button" id="review-next">跳过，下一项 →</button></div>`;
document.body.append(d);const $=s=>d.querySelector(s);let target=null,dirty=false,busy=false,queue=[];
const pending=u=>u.uncertain||u.translationStatus!=='complete';
const launcher=document.createElement('button');launcher.id='review-open';launcher.className='button subtle';launcher.textContent='复核';document.querySelector('.top-actions').prepend(launcher);
function refreshQueue(){const all=$('#review-filter').value==='all';queue=[];pages.forEach(p=>{p.units.filter(u=>!u.reviewOnly&&(all||pending(u))).forEach(u=>queue.push({id:u.id,page:p,unit:u}));if(p.reviewRequired)queue.push({id:p.id,page:p});});const count=units.filter(pending).length+pages.filter(p=>p.reviewRequired).length;launcher.textContent='复核'+(count?' · '+count:'');$('#review-count').textContent=`${count} 个待复核项 · 来源与人工修正始终保留`;renderList();}
function renderList(){const index=Math.max(0,queue.findIndex(q=>q.id===target?.id)),start=Math.max(0,index-20);$('#review-list').innerHTML=queue.slice(start,start+100).map(q=>`<button type="button" data-review-item="${esc(q.id)}" class="${q.id===target?.id?'active':''}"><small>${esc(q.page.source.file)} · ${q.page.number} 页</small><span>${esc(q.unit?q.unit.sourceText.slice(0,100)||'空白表格单元':'核对整页表格')}</span></button>`).join('')||'<p class="small muted">暂无待复核项。可切换到全部正文进行修正。</p>';}
async function api(path,body){const status=await fetch('/api/status').then(r=>r.json());const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Course-Token':status.token},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'请求失败');return value;}
function canLeave(){if(busy)return false;if(dirty){$('#review-error').textContent='有未保存修改，请先保存或撤销。';return false;}return true;}
function select(item){if(!item||!canLeave())return;target=item;const u=item.unit,p=item.page;$('#review-page-label').textContent=`${p.source.file} · 第 ${p.number} 页`;$('#review-page-image').src=p.image;$('#review-position').hidden=!u?.position;if(u?.position){const [x,y,x1,y1]=u.position;Object.assign($('#review-position').style,{left:x*100+'%',top:y*100+'%',width:(x1-x)*100+'%',height:(y1-y)*100+'%'});}$('#review-position-note').textContent=u?.positionEstimated?'紫框为估算位置，请结合整张表核对。':'紫框对应当前内容的原页位置。';$('#review-unit-fields').hidden=!u;$('#review-page-fields').hidden=!!u;$('#review-reset').hidden=!u;$('#review-source').value=u?.sourceText||'';$('#review-translation').value=u?.translatedText||'';$('#review-math').value=u?.latex||'';$('#review-math-label').hidden=u?.type!=='formula';$('#review-reason').textContent=u?(u.uncertaintyReason||(u.uncertain?'原文识别存疑，请对照左侧原页。':u.translationStatus!=='complete'?'译文未完成，可生成草稿后确认。':'手工修正正文。')):(p.reviewReasons||[]).join('；');$('#review-history').textContent=u?`${u.rawText||''}\n\n${JSON.stringify(u.corrections||[],null,2)}`:'';$('#review-error').textContent='';$('#review-draft-label').textContent='';$('#review-save').textContent=u?'保存并下一项':'确认本页已核对';renderList();}
function open(item){if(!canLeave())return;document.querySelector('#source-dialog')?.close();refreshQueue();select(item||queue[0]);if(!d.open)d.showModal();$('#review-form').hidden=!item&&!queue.length;if(!item&&!queue.length)$('#review-page-image').removeAttribute('src');}
launcher.onclick=()=>open();$('#review-close').onclick=()=>{if(canLeave())d.close();};d.addEventListener('cancel',e=>{if(!canLeave())e.preventDefault();});
$('#review-list').onclick=e=>{const b=e.target.closest('[data-review-item]');if(b)select(queue.find(q=>q.id===b.dataset.reviewItem));};
$('#review-filter').onchange=()=>{if(!canLeave()){$('#review-filter').value=$('#review-filter').value==='all'?'pending':'all';return;}refreshQueue();$('#review-form').hidden=!queue.length;select(queue[0]);};
function step(offset){if(!canLeave()||!queue.length)return;const index=queue.findIndex(q=>q.id===target?.id);select(queue[(index+offset+queue.length)%queue.length]);}
$('#review-prev').onclick=()=>step(-1);$('#review-next').onclick=()=>step(1);
$('#review-jump').onclick=()=>{if(!canLeave()||!target)return;d.close();document.dispatchEvent(new CustomEvent('course-navigate',{detail:target.id}));};
$('#review-reset').onclick=()=>{if(busy)return;dirty=false;select(target);};
$('#review-source').oninput=()=>{dirty=true;$('#review-draft-label').textContent='原文已修改。请更新对应译文，或生成新的草稿。';};$('#review-translation').oninput=$('#review-math').oninput=()=>{dirty=true;};
function setBusy(value,saving=false){busy=value;['#review-save','#review-translate','#review-reset'].forEach(s=>$(s).disabled=value);['#review-source','#review-translation','#review-math'].forEach(s=>$(s).disabled=value&&saving);}
$('#review-translate').onclick=async()=>{if(!target?.unit||busy)return;setBusy(true);const id=target.id,text=$('#review-source').value;$('#review-error').textContent='正在生成译文草稿…';try{const draft=await api('/api/review-translation/'+C.id,{contentId:id,sourceText:text});if(target.id!==id||$('#review-source').value!==text){$('#review-error').textContent='原文已变化，请重新生成草稿。';return;}$('#review-translation').value=draft.translatedText;dirty=true;$('#review-draft-label').textContent='AI 译文草稿，尚未写入正文；请核对后保存。';$('#review-error').textContent='';}catch(e){$('#review-error').textContent=e.message;}finally{setBusy(false);}};
$('#review-form').onsubmit=async e=>{e.preventDefault();if(!target||busy)return;const index=Math.max(0,queue.findIndex(q=>q.id===target.id)),u=target.unit;const body=u?{contentId:u.id,sourceText:$('#review-source').value,translatedText:$('#review-translation').value,latex:$('#review-math').value,expectedSourceText:u.sourceText,expectedTranslatedText:u.translatedText}:{pageId:target.page.id};if(u&&body.sourceText!==u.sourceText&&body.translatedText===u.translatedText&&u.type!=='formula'&&u.type!=='code'){$('#review-error').textContent='原文已改变，请更新译文后再保存。';return;}setBusy(true,true);try{const patch=await api('/api/review/'+C.id,body);document.dispatchEvent(new CustomEvent('course-review-updated',{detail:patch}));dirty=false;setBusy(false);refreshQueue();if(queue.length)select(queue[Math.min(index,queue.length-1)]);else{d.close();launcher.textContent='复核 · 已处理';}}catch(error){$('#review-error').textContent=error.message;}finally{setBusy(false);}};
d.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();$('#review-form').requestSubmit();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-review-unit],[data-review-page]');if(!b)return;const id=b.dataset.reviewUnit||b.dataset.reviewPage;const p=pages.find(p=>p.id===id||p.units.some(u=>u.id===id));if(p)open({id,page:p,unit:p.units.find(u=>u.id===id)});});
refreshQueue();
$('#review-page-image').onclick=()=>d.querySelector('.review-source-panel').classList.toggle('zoom');
})();
